name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
 
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-tooldotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Pack with dotnet
      run: dotnet pack src/Allegiance.Blazor.Highcharts/Allegiance.Blazor.Highcharts.csproj --output nuget-packages --configuration Release
    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_ACCOUNT }} --source https://api.nuget.org/v3/index.json
