name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/allegiance-consulting/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_ACCOUNT}}        

      - name: Build solution and generate NuGet package
        run: |  
          cd src/Allegiance.Blazor.Highcharts
          dotnet pack -c Release -o out  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./src/Allegiance.Blazor.Highcharts/out/*.nupkg --skip-duplicate --no-symbols true
